# Your Name or Company
title: pool [0AAAA]

# Description of your website. This is used for social sharing.
description:  Home of most secure and reliable Cardano pool - [0AAAA] pool

# A brief blurb about yourself
content: Welcome to the [0AAAA] pool's official website! In the Cardano universe, our pool is the most secure and reliable. Across Europe, we have several dedicated servers. Our pool operator has over 15 years of expertise in the telecommunications and banking sectors, having worked for some of the industry's most prestigious businesses and we have more than enough knowledge and experience to handle mission-critical operations. ID:2c799c3eb2fb59dbf874500fa77df18a2acaa8cfec1793c928294a50

# Add your social links
social:
  - platform: telegram
    url: https://t.me/pool0AAAA
#  - platform: facebook
#    url: https://facebook.com/brianmaierjr
  - platform: twitter
    url: https://twitter.com/pool0AAAA
#  - platform: linkedin
#    url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-210205947-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
